//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        public Good()
        {
            this.Admins = new HashSet<Admin>();
            this.Customers = new HashSet<Customer>();
            this.Drivers = new HashSet<Driver>();
        }
    
        public int GoodsId { get; set; }
        public string FromAdderess { get; set; }
        public string ToAddress { get; set; }
        public string GoodsType { get; set; }
        public Nullable<System.TimeSpan> Date { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual ICollection<Admin> Admins { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Driver> Drivers { get; set; }
    }
}
